
---

### ⚙️ `.streamlit/config.toml`

Crie a pasta `.streamlit` na raiz do projeto e dentro dela o arquivo `config.toml`:  

```toml
[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"
